[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  name = "About"
  pageRef = "about"
  weight = 20

[[main]]
  name = "Portfolio"
  pageRef = "portfolio"
  weight = 25

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 30

[[main]]
  name = "Services"
  pageRef = "services"
  weight = 40

[[main]]
  name = "Digital Products"
  pageRef = "products"
  weight = 60

[[footer]]
  name = "Home"
  url = "/"
  weight = 10

[[footer]]
  name = "Blog"
  pageRef = "posts"
  weight = 20

[[footer]]
  name = "Contact"
  pageRef = "services"
  weight = 30