baseURL = 'https://www.obedfavour.com/'
locale = 'en'
title = 'Obed Favour | AI Automation, n8n & Growth Marketing'
theme = 'blowfish'

googleAnalytics = "G-KMPF4JH5CX"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true